[package]
name = "kbm"
version = "0.1.0"
authors = ["izzymg <izzymhg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11rb = "0.3.0"
rand = "0.7"